# Generated by Django 2.1.5 on 2019-10-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='antivirus_expire_date',
            new_name='antivirus_expiry_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='in_home_hardware_service_expire_date',
            new_name='in_home_hardware_service_expiry_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='office_expire_date',
            new_name='office_expiry_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='warranty_expire_date',
            new_name='warranty_expiry_date',
        ),
    ]
