# Generated by Django 2.1.5 on 2019-10-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20191018_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='office_data',
            field=models.CharField(default='Home and student', max_length=30),
        ),
    ]
