# Generated by Django 2.1.5 on 2019-10-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_customer_office_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='office_data',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
