# Generated by Django 2.1.5 on 2019-10-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_auto_20191020_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='model',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
