# Generated by Django 2.1.5 on 2019-10-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_customer_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='model',
            new_name='sys_model',
        ),
    ]
