# Generated by Django 2.1.5 on 2019-10-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_auto_20191020_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sys_model',
        ),
    ]
