# Generated by Django 2.1.5 on 2019-10-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0008_customer_sys_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sys_model',
        ),
    ]
