# Generated by Django 2.1.5 on 2019-10-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0009_remove_customer_sys_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accessories',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='sys_model',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
