# Generated by Django 2.1.5 on 2019-10-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0010_auto_20191020_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='accessories',
        ),
    ]
